name: Deploy NestJS to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build and package
      run: npm run package

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  # Change this to your AWS region

    - name: Upload to S3
      run: |
        aws s3 cp function.zip s3://congro-ui-deployment-bucket-us-west-1/function-${{ github.sha }}.zip


    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name congro-ui \
          --s3-bucket congro-ui-deployment-bucket-us-west-1 \
          --s3-key function-${{ github.sha }}.zip
